[build]
  command = """
    git clone https://github.com/flutter/flutter.git -b stable --depth 1
    export PATH="$PATH:$(pwd)/flutter/bin"
    flutter build web --release
  """
  publish = "build/web"

[build.environment]
  NODE_VERSION = "20"


  SUPABASE_URL = "https://tjzphihmvagmmfwqpjjn.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqenBoaWhtdmFnbW1md3FwampuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDg2MDUsImV4cCI6MjA3MjMyNDYwNX0.18RLWI9Rgnm-E_o_4S7GsiAZULPpYZMkkBUBjdcKvqs"

  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_URL,SUPABASE_ANON_KEY"
