[build]
  command = """
    git clone https://github.com/flutter/flutter.git -b stable --depth 1
    export PATH="$PATH:$(pwd)/flutter/bin"
    flutter build web --release
  """
  publish = "build/web"

[build.environment]
  NODE_VERSION = "20"


  SUPABASE_URL = "https://xxxxx.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1..."

  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_URL,SUPABASE_ANON_KEY"
