[build]
  command = """
    git clone https://github.com/flutter/flutter.git -b stable --depth 1
    export PATH="$PATH:$(pwd)/flutter/bin"
    flutter build web --release
  """
  publish = "build/web"

[build.environment]
  NODE_VERSION = "20"